#ifndef RVTEST_CONFIG_H
#define RVTEST_CONFIG_H
#define XLEN64

#define I_SUPPORTED
#define M_SUPPORTED
#define A_SUPPORTED
#define C_SUPPORTED
#define ZAAMO_SUPPORTED
#define ZALRSC_SUPPORTED
#define ZCA_SUPPORTED
#define ZICSR_SUPPORTED
#define ZICNTR_SUPPORTED
#define ZIFENCEI_SUPPORTED
#define CONFORMING_SM_SUPPORTED

#define S_SUPPORTED
#define U_SUPPORTED

#define SSTC_SUPPORTED

#define SV39_SUPPORTED
#define SVADE_SUPPORTED
#define SVBARE_SUPPORTED

#define RVMODEL_PMP_GRAIN 0
#define RVMODEL_NUM_PMPS 0

#define TIME_CSR_IMPLEMENTED 1

#ifndef RAM_BASE_ADDR
#define RAM_BASE_ADDR 0x80000000
#endif

#ifndef LARGEST_PROGRAM
#define LARGEST_PROGRAM 0x00010000
#endif

#ifndef CLINT_BASE_ADDRESS
#define CLINT_BASE_ADDRESS 0x02000000
#endif

#ifndef RVMODEL_MSIP_ADDRESS
#define RVMODEL_MSIP_ADDRESS (CLINT_BASE_ADDRESS + 0x0)
#endif

#endif /* RVTEST_CONFIG_H */
